# Generated by Django 2.1.1 on 2019-06-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150, unique=True)),
                ('Year', models.CharField(max_length=100)),
                ('Rated', models.CharField(blank=True, max_length=100)),
                ('Released', models.CharField(max_length=100)),
                ('Runtime', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=150)),
                ('Writer', models.CharField(max_length=1000)),
                ('Actors', models.CharField(max_length=1000)),
                ('Plot', models.CharField(blank=True, max_length=1000)),
                ('Language', models.CharField(blank=True, max_length=100)),
                ('Country', models.CharField(blank=True, max_length=100)),
                ('Awards', models.CharField(blank=True, max_length=100)),
                ('Poster', models.CharField(blank=True, max_length=1000)),
                ('Metascore', models.CharField(blank=True, max_length=100)),
                ('imdbRating', models.CharField(blank=True, max_length=100)),
                ('imdbVotes', models.CharField(blank=True, max_length=100)),
                ('imdbID', models.CharField(blank=True, max_length=100)),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('DVD', models.CharField(blank=True, max_length=100)),
                ('BoxOffice', models.CharField(blank=True, max_length=100)),
                ('Production', models.CharField(blank=True, max_length=100)),
                ('Website', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
