# Generated by Django 2.1.1 on 2019-06-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0003_auto_20190605_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='source',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
